import 'package:predator_pest/app/common_imports/common_imports.dart';

class AppLocalization extends Translations {
  @override
  Map<String, Map<String, String>> get keys {
    return {
      'en': enEN,
    };
  }

  static final Map<String, String> enEN = {
    'somethingWentWrong': 'Something went wrong',
    'readMore': 'Read More',
    'readLess': 'Read Less',
    'skip': 'Skip',
    'onBoardingTitle1': 'Your Shield Against Unwanted Guests',
    'onBoardingTitle2': 'Evicting Pests, Restoring Peace.',
    'onBoardingDescription1': 'Simply dummy text of the printing and typesetting industry.',
    'onBoardingDescription2': 'Simply dummy text of the printing and typesetting industry.',
    'next': 'Next',
    'dateFormat': 'DD/MM/YYYY',
    'emailAddress': 'Email Address',
    'enterYourEmailAddress': 'Enter Your Email Address',
    'password': 'Password',
    'forgotPassword': 'Forgot Password?',
    'login': 'Login',
    'checkListTitle': 'Please Submit your remark by selecting following options',
    'typeHere': 'Type Here',
    'submit': 'Submit',
    'noMediaFound': 'No Media Found!',
    'uploadImagesFromMediaLibrary': 'Upload Images From Media Library',
    'uploadFile': 'Upload File',
    'dontHaveAnAccount': 'Already have an account?',
    'enterYourRegisteredEmailAddress': 'Enter your registered email address',
    'resetPassword': 'Reset Password',
    'description': 'Description',
    'writeHere': 'Write Here',
    'clickWithCamera': 'Click with camera',
    'account': 'Account',
    'welcomeBack': 'Welcome back',
    'pestProblems': 'Pest Problems',
    'sanitationIssues': 'Sanitation Issues',
    'structuralIssues': 'Structural Issues',
    'recommendCorrectiveMeasures': 'Recommend Corrective Measures',
    'inspectionMonitorResults': 'Inspection/Monitor Results',
    'selectLocations': 'Select Locations',
    'accountFieldShouldNotBeEmpty': 'Account Field should not be empty',
    'appPermission': 'App Permission',
    'permissionGrantCamera': 'This app needs camera permission to use this feature. You can grant it in app setting',
    'permissionGrantLocation':
        'This app needs location permission to use this feature. You can grant it in app setting.',
    'settings': 'Settings',
    'success': 'Success!',
    'emailIdCanNotBeEmpty': 'Email id can not be empty',
    'emailIdIsNotValid': 'Email id is not valid',
    'passwordCanNotBeEmpty': 'Password can not be empty',
    'loginSuccessful': 'Login Successful',
    'successful': 'Successful!',
    'successMessage':
        'Your request has been submitted successfully!. If you need any assistant then contact us on given details.',
    'needHelp': 'NEED HELP?',
    'jamesDeBari': 'James DeBari',
    'mediaUploadedSuccessfully': 'Media uploaded successfully',
    'pleaseSelectImage': 'Please select image',
    'youAreAbleToUploadOnlyImages': 'You are able to upload only 6 images',
    'noInternetConnection': 'No Internet Connection',
    'pleaseCheckYourInternetConnectionAndTryAgain': 'Please check your internet connection and try again.',
    'tryAgain': 'Try Again',
    'areYouSure': 'Are you sure?',
    'doYouWantToLogout': 'Do you want to logout?',
    'yes': 'Yes',
    'no': 'No',
    'lastName': 'Last Name',
    'firstName': 'First Name',
    'profile': 'Profile',
    'permissionGrantStorage': 'This app needs storage permission to use this feature. You can grant it in app setting',
    'dateOfBirth': 'Date of birth',
    'phoneNumber': 'Phone number',
    'location': 'Location',
  };
}
